### PR TITLE
add Distributions and Sesame

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Some files were omitted because the csv and jasp file names are not the same (probably?). This adds those files in a single folder (one for discovering distributions and one for bain). I was not able to automate the extracting of html, so could you maybe add those if that's a quick thing?

### CODE REVIEW

**Comment by JohnnyDoorn** [comment]
Reminder @RensDofferhoff (=

**Review by RensDofferhoff — APPROVED** [review]
oooops

**Comment by JohnnyDoorn** [comment]
Haha no worries! and is there a way to do the auto-extracting of html? can also discuss in person tomorrow!

**Comment by RensDofferhoff** [comment]
Lets discuss it tomorrow! :)

**Pull request merged**
